project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on Ex/Hands-on_Ex01/Hand-on_Ex1.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on Ex/Hands-on_Ex02/hand-on-ex.html"

    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    toc: true

editor: visual
